#cloud-config

package_update: true

packages:
  - podman
  - wget

runcmd:
  - wget -O /tmp/script.sh https://source.brenans.sh/esteban/VaultWarden/raw/branch/main/script.sh
  - chmod +x /tmp/script.sh
  - su -c '/tmp/script.sh' - rocky

final_message: "The system is finally up, after $UPTIME seconds"
